version: "3"

services:
  blockgametracker:
    build: .
    image: ghcr.io/polargh/blockgametracker
    ports:
      - "9900:9900"
    environment:
      CONFIG_FILE: "/config/servers.yaml"
    volumes:
      - ./deploy/config:/config