java:
  - name: "The Yard"
    address: "play.yardpodcast.cc"
  - name: "Hideaway"
    address: "playhideaway.com"
  - name: "MCParks"
    address: "main.mcparks.us"
  - name: "Imagine Fun"
    address: "play.imaginefun.net"
  - name: "World of Wonders"
    address: "server.world-of-wonders.net"
  - name: "Coaster Con"
    address: "coastercon.net"
